### PR TITLE
replacing big if by a switch and get/set quaternion support

### PR DESCRIPTION
**Pull request by BenjaminNavarro**
As the title suggests, I added the possibility to get or set an object's quaternion from the remote api and I replaced the huge section of `if` by a `switch/case` for better performance

### CODE REVIEW

**Comment by Coppelia** [comment]
Thanks again Benjamin!

**Comment by BenjaminNavarro** [comment]
no problem, I think I'll continue to add stuff as I need it.

By the way, is there an easy way to generate the remoteApi bindings instead of doing everything manually?

**Comment by Coppelia** [comment]
Unfortunately no, different people wrote the various bindings, and we kept manually adding functions. At the same time, we should not expect the remote API to change much more, since we are preparing another way to communicate between V-REP and external applications in a much more powerful and cleaner way, based on ZMQ and protocol buffers... a kind of lightweight ROS middleware...

**Comment by BenjaminNavarro** [comment]
Great idea to move to ZMQ, it should make things a lot better.

Looking forward to it!

**Pull request merged**
